twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_name: '%app_name%'
        avatars_dir: '%avatars_dir%'
        posts_dir: '%posts_dir%'
    date:
        format: d-m-Y H:i

when@test:
    twig:
        strict_variables: true
