controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app/config/route/liip_imagine.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
